os: linux
arch: ppc64le
dist: focal
sudo: required
services:
  - docker
language: go
go:
- "1.16.x"

script:
- chmod +x ./build.sh
- source ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./terraform/terraform
  skip_cleanup: true
  draft: true
