name: Build Terraform on Power

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Install dependencies and build Terraform
        id: build
        with:
          arch: ppc64le
          distro: ubuntu20.04
          
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
      
          run: |
            apt-get update -y
            apt-get install -y git wget build-essential
            
            #Building terraform
            chmod +x ./build.sh
            source ./build.sh v0.13.5
            echo '::set-output name=RELEASE::'$TAG
            
            #Copy built binary file to artifacts directory
            cp $GOPATH/bin/terraform /artifacts/terraform-$TAG
            
            #Check if release exists
            echo '::set-output name=RELEASE_EXISTS::'$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/snehakpersistent/terraform-ppc64le/releases/tags/$TAG)
                      
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.build.outputs.RELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: ./artifacts/terraform-${{ steps.build.outputs.RELEASE }}
          name: ${{ steps.build.outputs.RELEASE }}
          replacesArtifacts: true
          draft: false
          prerelease: false 
      
